<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Pacientes\NewFolder\**" />
    <EmbeddedResource Remove="Pacientes\NewFolder\**" />
    <None Remove="Pacientes\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlanesRecetas.domain\PlanesRecetas.domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Joseco.DDD.Core">
      <HintPath>..\joseco.ddd.core\src\Joseco.DDD.Core\bin\Debug\net8.0\Joseco.DDD.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
